using Neo.L2.Executor.Effects;
using Neo.SmartContract;
using Neo.VM.Types;
using Array = Neo.VM.Types.Array;
using Buffer = Neo.VM.Types.Buffer;

namespace Neo.L2.Executor.UnitTests;

/// <summary>Cross-language conformance tests for N4 genesis V1 execution effects.</summary>
/// <remarks>Golden bytes were generated by <c>neo-execution-core</c> at <c>ecbf53e</c>.</remarks>
[TestClass]
public class UT_CanonicalExecutionEffects
{
    [TestMethod]
    public void EmptyEffects_MapBothHashesToUInt256Zero()
    {
        Assert.AreEqual(UInt256.Zero, CanonicalExecutionEffects.Empty.StorageHash);
        Assert.AreEqual(UInt256.Zero, CanonicalExecutionEffects.Empty.EventsHash);
    }

    [TestMethod]
    public void StorageV1_MatchesRustGoldenPreimageAndHash()
    {
        var changes = GoldenChanges();

        CollectionAssert.AreEqual(
            Convert.FromHexString(CanonicalEffectsGolden.StoragePreimage),
            CanonicalEffectsHasher.SerializeStorage(changes));
        CollectionAssert.AreEqual(
            Convert.FromHexString(CanonicalEffectsGolden.StorageHash),
            CanonicalEffectsHasher.HashStorage(changes).GetSpan().ToArray());
    }

    [TestMethod]
    public void StackStateV1_MatchesRustRecursiveGolden()
    {
        CollectionAssert.AreEqual(
            Convert.FromHexString(CanonicalEffectsGolden.StackState),
            CanonicalStackStateSerializer.Serialize(GoldenFirstState()));
    }

    [TestMethod]
    public void EventsV1_MatchesRustGoldenPreimageAndHash()
    {
        var effects = GoldenEffects();

        CollectionAssert.AreEqual(
            Convert.FromHexString(CanonicalEffectsGolden.EventsPreimage),
            CanonicalEffectsHasher.SerializeEvents(effects.Events));
        CollectionAssert.AreEqual(
            Convert.FromHexString(CanonicalEffectsGolden.EventsHash),
            effects.EventsHash.GetSpan().ToArray());
    }

    [TestMethod]
    public void StorageV1_RejectsNonCanonicalOrderDuplicateAndPresence()
    {
        var changes = GoldenChanges();

        Assert.ThrowsExactly<ArgumentException>(
            () => CanonicalEffectsHasher.SerializeStorage([changes[1], changes[0]]));
        Assert.ThrowsExactly<ArgumentException>(
            () => CanonicalEffectsHasher.SerializeStorage([changes[0], changes[0]]));
        Assert.ThrowsExactly<ArgumentException>(() => CanonicalEffectsHasher.SerializeStorage(
            [Change([0x01], CanonicalStorageOperation.Add, [0x10], [0x11])]));
        Assert.ThrowsExactly<ArgumentException>(() => CanonicalEffectsHasher.SerializeStorage(
            [Change([0x01], CanonicalStorageOperation.Update, null, [0x11])]));
        Assert.ThrowsExactly<ArgumentException>(() => CanonicalEffectsHasher.SerializeStorage(
            [Change([0x01], CanonicalStorageOperation.Delete, [0x10], [0x11])]));
    }

    [TestMethod]
    public void Create_SortsCompleteRawKeysBeforeHashing()
    {
        var changes = GoldenChanges();
        var effects = CanonicalExecutionEffects.Create(
            [changes[2], changes[0], changes[1]],
            []);

        CollectionAssert.AreEqual(changes[0].Key.ToArray(), effects.StorageChanges[0].Key.ToArray());
        CollectionAssert.AreEqual(changes[1].Key.ToArray(), effects.StorageChanges[1].Key.ToArray());
        CollectionAssert.AreEqual(changes[2].Key.ToArray(), effects.StorageChanges[2].Key.ToArray());
        CollectionAssert.AreEqual(
            Convert.FromHexString(CanonicalEffectsGolden.StorageHash),
            effects.StorageHash.GetSpan().ToArray());
    }

    [TestMethod]
    public void EventsV1_BindsOrderAndCompleteParameters()
    {
        var first = Event(Enumerable.Range(0, UInt160.Length).Select(static value => (byte)value).ToArray(), "Changed", GoldenFirstState());
        var second = Event(Enumerable.Range(0, UInt160.Length).Select(static value => (byte)(0xe0 + value)).ToArray(), "Δ", GoldenSecondState());
        var baseline = CanonicalExecutionEffects.Create([], [first, second]);
        var reversed = CanonicalExecutionEffects.Create([], [second, first]);
        var changed = CanonicalExecutionEffects.Create(
            [],
            [Event(first.ScriptHash.GetSpan().ToArray(), "Changed", new Array(null, [new Integer(2)])), second]);

        Assert.AreNotEqual(baseline.EventsHash, reversed.EventsHash);
        Assert.AreNotEqual(baseline.EventsHash, changed.EventsHash);
    }

    [TestMethod]
    public void StackStateV1_RejectsUnsupportedInteropAndExcessiveDepth()
    {
        Assert.ThrowsExactly<InvalidOperationException>(
            () => CanonicalStackStateSerializer.Serialize(new InteropInterface(new object())));

        StackItem state = StackItem.Null;
        for (var depth = 0; depth < 18; depth++) state = new Array(null, [state]);
        Assert.ThrowsExactly<InvalidOperationException>(
            () => CanonicalStackStateSerializer.Serialize(state));
    }

    [TestMethod]
    public void StorageChange_ContentEqualityHashAndCopyUseBytes()
    {
        var key = new byte[] { 0x01 };
        var oldValue = new byte[] { 0x10 };
        var newValue = new byte[] { 0x11 };
        var change = Change(key, CanonicalStorageOperation.Update, oldValue, newValue);
        var equal = Change([0x01], CanonicalStorageOperation.Update, [0x10], [0x11]);

        Assert.IsFalse(change.Equals(null));
        Assert.IsTrue(change.Equals(change));
        Assert.AreEqual(change, equal);
        Assert.AreEqual(change.GetHashCode(), equal.GetHashCode());
        Assert.AreNotEqual(change, equal with { Operation = CanonicalStorageOperation.Add });
        Assert.AreNotEqual(change, equal with { Key = new byte[] { 0x02 } });
        Assert.AreNotEqual(change, equal with { OldValue = null });
        Assert.AreNotEqual(change, equal with { OldValue = new byte[] { 0x12 } });
        Assert.AreNotEqual(change, equal with { NewValue = null });
        Assert.AreNotEqual(change, equal with { NewValue = new byte[] { 0x13 } });

        var copy = CanonicalExecutionEffects.Create([change], []).StorageChanges.Single();
        key[0] = 0xFF;
        oldValue[0] = 0xFF;
        newValue[0] = 0xFF;
        CollectionAssert.AreEqual(new byte[] { 0x01 }, copy.Key.ToArray());
        CollectionAssert.AreEqual(new byte[] { 0x10 }, copy.OldValue!.Value.ToArray());
        CollectionAssert.AreEqual(new byte[] { 0x11 }, copy.NewValue!.Value.ToArray());

        var add = Change([0x03], CanonicalStorageOperation.Add, null, [0x30]);
        Assert.AreEqual(
            add,
            CanonicalExecutionEffects.Create([add], []).StorageChanges.Single());
        _ = add.GetHashCode();
    }

    [TestMethod]
    public void ExecutionEvent_ContentEqualityHashAndCopyUseBytes()
    {
        var state = new byte[] { 0x01, 0x02 };
        var @event = new CanonicalExecutionEvent
        {
            ScriptHash = new UInt160(Enumerable.Repeat((byte)0x10, UInt160.Length).ToArray()),
            EventName = "Changed",
            State = state,
        };
        var equal = new CanonicalExecutionEvent
        {
            ScriptHash = new UInt160(Enumerable.Repeat((byte)0x10, UInt160.Length).ToArray()),
            EventName = "Changed",
            State = new byte[] { 0x01, 0x02 },
        };

        Assert.IsFalse(@event.Equals(null));
        Assert.IsTrue(@event.Equals(@event));
        Assert.AreEqual(@event, equal);
        Assert.AreEqual(@event.GetHashCode(), equal.GetHashCode());
        Assert.AreNotEqual(@event, equal with { ScriptHash = UInt160.Zero });
        Assert.AreNotEqual(@event, equal with { EventName = "changed" });
        Assert.AreNotEqual(@event, equal with { State = new byte[] { 0x02 } });

        state[0] = 0xFF;
    }

    [TestMethod]
    public void Hashers_RejectUnsupportedVersionsAndMalformedStorageChanges()
    {
        var change = Change([0x01], CanonicalStorageOperation.Add, null, [0x10]);
        var @event = new CanonicalExecutionEvent
        {
            ScriptHash = UInt160.Zero,
            EventName = "Changed",
            State = new byte[] { 0x01 },
        };
        var invalidVersion = (CanonicalEffectsVersion)0xFF;

        Assert.ThrowsExactly<ArgumentOutOfRangeException>(
            () => CanonicalEffectsHasher.HashStorage([change], invalidVersion));
        Assert.ThrowsExactly<ArgumentOutOfRangeException>(
            () => CanonicalEffectsHasher.HashEvents([@event], invalidVersion));
        Assert.ThrowsExactly<ArgumentException>(() => CanonicalEffectsHasher.SerializeStorage(
            [Change([], CanonicalStorageOperation.Add, null, [0x10])]));
        Assert.ThrowsExactly<ArgumentOutOfRangeException>(() => CanonicalEffectsHasher.SerializeStorage(
            [Change([0x01], (CanonicalStorageOperation)0xFF, null, [0x10])]));
    }

    internal static CanonicalExecutionEffects GoldenEffects()
        => CanonicalExecutionEffects.Create(
            GoldenChanges(),
            [
                Event(
                    Enumerable.Range(0, UInt160.Length).Select(static value => (byte)value).ToArray(),
                    "Changed",
                    GoldenFirstState()),
                Event(
                    Enumerable.Range(0, UInt160.Length).Select(static value => (byte)(0xe0 + value)).ToArray(),
                    "Δ",
                    GoldenSecondState()),
            ]);

    private static CanonicalStorageChange[] GoldenChanges()
        =>
        [
            Change([0x00, 0xff], CanonicalStorageOperation.Add, null, []),
            Change([0x01], CanonicalStorageOperation.Update, [0x10, 0x20], [0x10, 0x21, 0x22]),
            Change([0x01, 0x00], CanonicalStorageOperation.Delete, [], null),
        ];

    private static Array GoldenFirstState()
    {
        var map = new Map(null);
        map[new ByteString(new byte[] { (byte)'k' })] = new Array(
            null,
            [StackItem.False, new Integer(0x7f)]);
        return new Array(
            null,
            [
                StackItem.Null,
                StackItem.True,
                new Integer(0),
                new Integer(128),
                new Integer(-128),
                new ByteString(new byte[] { 0xaa, 0xbb }),
                new Buffer(new byte[] { 0xcc }),
                new Struct(null, [new Integer(-1)]),
                map,
            ]);
    }

    private static Array GoldenSecondState() => new(null, [new Integer(1)]);

    private static CanonicalStorageChange Change(
        byte[] key,
        CanonicalStorageOperation operation,
        byte[]? oldValue,
        byte[]? newValue)
        => new()
        {
            Key = key,
            Operation = operation,
            OldValue = Optional(oldValue),
            NewValue = Optional(newValue),
        };

    private static ReadOnlyMemory<byte>? Optional(byte[]? value)
    {
        if (value is null) return null;
        return new ReadOnlyMemory<byte>(value);
    }

    private static NotifyEventArgs Event(byte[] scriptHash, string name, Array state)
        => new(null, new UInt160(scriptHash), name, state);
}

internal static class CanonicalEffectsGolden
{
    internal const string StackState = "4e454f3453544b310100000040090000000020012100000000210200000080002101000000802802000000aabb3001000000cc41010000002101000000ff480100000028010000006b4002000000200021010000007f";
    internal const string StoragePreimage = "6e656f2d6e342f73746f726167652d64656c74612f763100030000000200000000ff0100010000000001000000010201020000001020010300000010212202000000010003010000000000";
    internal const string StorageHash = "f29d97c22bb7fa8ac18c492e72a32e21bf9b78604c1311f6614e605d87f29c00";
    internal const string EventsPreimage = "6e656f2d6e342f6576656e74732f76310002000000000102030405060708090a0b0c0d0e0f10111213070000004368616e676564560000004e454f3453544b310100000040090000000020012100000000210200000080002101000000802802000000aabb3001000000cc41010000002101000000ff480100000028010000006b4002000000200021010000007fe0e1e2e3e4e5e6e7e8e9eaebecedeeeff0f1f2f302000000ce94170000004e454f3453544b31010000004001000000210100000001";
    internal const string EventsHash = "cbaa7735729a1aba52fa898e993d063c25fe868b301ff207ecdd6371caeed337";
    internal const string Receipt = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f010807060504030201f29d97c22bb7fa8ac18c492e72a32e21bf9b78604c1311f6614e605d87f29c00cbaa7735729a1aba52fa898e993d063c25fe868b301ff207ecdd6371caeed337";
    internal const string ReceiptHash = "57164ab3242e2ff92bd5ecd031738c05432da52fde9781976617cfa2f02b9adc";
}
